### ISSUE TITLE
no field or member function named 'standardOptimizeOption' in 'build.Builder'

### ISSUE THREAD

**Issue by user6879** [kristoff-it/zig-doctest#15]
Hi there! I'm new to zig. I tried to compile `zig-doctest` but it threw an error.

Zig version: 0.11.0-dev.1364+72c09b7b3

![image](https://i.imgur.com/Ye2oXTJ.png)

What I did wrong?

**Comment by nektro** [comment]
you didnt do anything wrong, you're using a newer zig version than it was currently built with. only needs a code update

**Comment by user6879** [comment]
> you didnt do anything wrong, you're using a newer zig version than it was currently built with. only needs a code update

what version do i need?

**Comment by nektro** [comment]
0.11.0-dev.1570+693b12f8e or greater

**Comment by user6879** [comment]
Oh, it worked!

zig version: `0.11.0-dev.1648+c993af623`

Thanks!!!
