### ISSUE TITLE
error: no member named 'standardOptimizeOption' in struct 'std.build.Builder'

### ISSUE THREAD

**Issue by harshrathod50** [kristoff-it/zig-doctest#22]
I installed zig on my Fedora 39 but upon building doctest I get the below error:

```bash
./build.zig:12:23: error: no member named 'standardOptimizeOption' in struct 'std.build.Builder'
    const optimize = b.standardOptimizeOption(.{});
```

**Comment by nektro** [comment]
zig-doctest uses zig master

**Comment by harshrathod50** [comment]
Can you please elaborate so that I can better understand?

**Comment by nektro** [comment]
if you do `zig version` in a terminal my guess is that you'd see 0.11.0. whereas doctest is built to support the latest/master/nightly version from https://ziglang.org/download/

**Comment by harshrathod50** [comment]
Okay, so do i need to download source and build and install zig? My current version is `0.9`?

**Comment by nektro** [comment]
either that or download a tarball from the link yes

**Comment by harshrathod50** [comment]
Thanks, I followed the latter option and downloaded the latest tarball and then built `zig-doctest` and it was successful.
